using VolleyballInfo.DataGathererService.Application.Abstractions.Messaging;

namespace VolleyballInfo.DataGathererService.Application.VolleyballInformation.GatherVolleyballInformation;

public sealed record GatherNationsLeagueInformationCommand : ICommand;