using VolleyballInfo.DataGathererService.Application.Abstractions.Messaging;

namespace VolleyballInfo.DataGathererService.Application.VolleyballInformation.GatherNationsLeagueInformation;

public sealed record GatherNationsLeagueInformationCommand : ICommand;